name: Python CI

on: push

jobs:
    ci:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                python-version: [3.7, 3.8, 3.9]
        steps:
            - uses: actions/checkout@main
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@main
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Display Python version
              run: python -c "import sys; print(sys.version)"
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip wheel setuptools
                  pip install -r requirements.txt
            - name: Test run
              run: python app/app.py
